<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ $title }}</title>
    <style>
        body { font-family: DejaVu Sans, sans-serif; color: #111827; font-size: 12px; }
        h1 { font-size: 18px; margin: 0 0 10px; }
        .content img { max-width: 100%; height: auto; }
        .content { line-height: 1.5; }
        .meta { color: #6b7280; margin-bottom: 14px; }
    </style>
</head>
<body>
    <h1>{{ $title }}</h1>
    <div class="meta">Generated by Academix</div>
    <div class="content">{!! $contentHtml !!}</div>
</body>
</html>

